import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, fonts } from "../../styles/theme";
import ProfilePageHeader from "../../components/ui/profile-page-header";
import type { RootStackParamList } from "../../types/navigation";
type P = NativeStackScreenProps<RootStackParamList, "PrivacyPolicy">;
const Card = ({ title, children, dark = false }: {
    title: string;
    children: React.ReactNode;
    dark?: boolean;
}) => <View style={[s.card, dark && s.dark]}><View style={s.head}><Ionicons name="shield-checkmark-outline" size={19} color={colors.lime}/><Text style={[s.cardTitle, dark && s.white]}>{title}</Text></View>{children}</View>;
export default function Privacy({ navigation }: P) { return <SafeAreaView style={s.safe} edges={[]}><ProfilePageHeader title="Privacy Policy" onBack={() => navigation.goBack()}/><ScrollView contentContainerStyle={s.content}><View style={s.commit}><View style={s.bar}/><Text style={s.commitTitle}>Our Commitment</Text><Text style={s.body}>At <Text style={s.green}>CommunityConnect</Text>, your privacy is the cornerstone of our social ecosystem. We believe that meaningful community building can only thrive on a foundation of trust and transparency.</Text></View><Card title="Information We Collect"><Text style={s.body}>- <Text style={s.bold}>Personal Details:</Text> Name, email address, and profile biography to facilitate authentic interactions.{"\n\n"} - <Text style={s.bold}>Event Participation:</Text> History of events attended, RSVPs, and hosting metrics.{"\n\n"} - <Text style={s.bold}>Community Interactions:</Text> Group memberships, posts, and comments.</Text></Card><Card title="How We Use Your Data"><View style={s.inner}><Text style={s.smallGreen}>EXPERIENCE</Text><Text style={s.body}>Improving our services and tailoring community recommendations to your urban lifestyle.</Text></View><View style={s.inner}><Text style={s.smallGreen}>SAFETY</Text><Text style={s.body}>Maintaining community guidelines and ensuring a secure environment for all members.</Text></View></Card><Card dark title="Data Sharing & Partners"><Text style={[s.body, s.white]}>We never sell your data. We only share necessary information with trusted third-party partners to facilitate core services.</Text><View style={s.payment}><Ionicons name="card-outline" size={24} color={colors.ink}/><Text style={s.payText}>Financial Security{"\n"}Payment processing via Paystack (Encrypted & Secure).</Text></View></Card><Card title="Your Rights"><Text style={s.right}>Right to Access{"\n"}<Text style={s.rightBody}>Request a full copy of all data we hold about your account.</Text>{"\n\n"}Right to Correction{"\n"}<Text style={s.rightBody}>Update or rectify any inaccurate personal information.</Text>{"\n\n"}Right to Deletion{"\n"}<Text style={s.rightBody}>Permanently erase your account and associated data from our servers.</Text></Text></Card><Pressable style={s.button}><Text style={s.btnText}>Contact Privacy Team</Text></Pressable><Text style={s.updated}>Last updated: October 24, 2023</Text></ScrollView></SafeAreaView>; }
;
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, nav: { alignItems: "center", backgroundColor: colors.white, flexDirection: "row", height: 54, paddingHorizontal: 22 }, navTitle: { color: colors.ink, fontFamily: fonts.bold, fontSize: 16, marginLeft: 20 }, navIcon: { alignItems: "center", backgroundColor: "#e9fbf0", borderRadius: 18, height: 36, justifyContent: "center", marginLeft: "auto", width: 36 }, content: { padding: 20, paddingBottom: 38 }, commit: { backgroundColor: colors.white, borderRadius: 28, elevation: 2, padding: 21 }, bar: { backgroundColor: colors.lime, borderRadius: 2, height: 27, left: 21, position: "absolute", top: 21, width: 6 }, commitTitle: { color: colors.ink, fontFamily: fonts.extraBold, fontSize: 21, marginLeft: 17 }, body: { color: "#26352e", fontFamily: fonts.medium, fontSize: 13, lineHeight: 19, marginTop: 13 }, green: { color: "#00a94f" }, bold: { fontFamily: fonts.bold }, card: { backgroundColor: colors.white, borderRadius: 28, elevation: 2, marginTop: 14, padding: 21 }, dark: { backgroundColor: "#153f29" }, head: { alignItems: "center", flexDirection: "row", gap: 13 }, cardTitle: { color: colors.ink, fontFamily: fonts.bold, fontSize: 16 }, white: { color: colors.white }, inner: { backgroundColor: "#f7fbf9", borderRadius: 15, marginTop: 12, padding: 13 }, smallGreen: { color: "#00a94f", fontFamily: fonts.bold, fontSize: 10 }, payment: { alignItems: "center", backgroundColor: "#617a6b", borderRadius: 24, flexDirection: "row", gap: 12, marginTop: 16, padding: 12 }, payText: { color: colors.white, fontFamily: fonts.medium, fontSize: 12, lineHeight: 17 }, right: { color: colors.ink, fontFamily: fonts.bold, fontSize: 14, lineHeight: 20, marginTop: 14 }, rightBody: { color: "#168d50", fontFamily: fonts.medium, fontSize: 13 }, button: { alignSelf: "center", backgroundColor: colors.lime, borderRadius: 24, elevation: 3, marginTop: 27, paddingHorizontal: 23, paddingVertical: 13 }, btnText: { color: colors.ink, fontFamily: fonts.bold, fontSize: 14 }, updated: { color: "#218d50", fontFamily: fonts.medium, fontSize: 11, marginTop: 15, textAlign: "center" } });
