import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, fonts } from "../../styles/theme";
import ProfilePageHeader from "../../components/ui/profile-page-header";
import type { RootStackParamList } from "../../types/navigation";
type P = NativeStackScreenProps<RootStackParamList, "TermsConditions">;
const data = [["Acceptance of Terms", "By accessing or using the CommunityConnect application, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use our services."], ["User Responsibilities", "Users are expected to maintain a respectful and safe environment. You are responsible for maintaining the confidentiality of your account credentials, providing accurate information, and conducting yourself professionally during community events."], ["Event Hosting Guidelines", "Hosts must provide accurate event descriptions and adhere to local safety regulations. CommunityConnect reserves the right to remove any event that violates community standards or promotes illegal activities."], ["Payment & Refunds", "All transactions are processed through secure third-party providers. Refund requests must be submitted at least 48 hours prior to the event start time."], ["Account Termination", "We reserve the right to suspend or terminate your account at our sole discretion for conduct that we believe violates these Terms and Conditions."]];
export default function Terms({ navigation }: P) { return <SafeAreaView style={s.safe} edges={[]}><ProfilePageHeader title="Terms & Conditions" onBack={() => navigation.goBack()}/><ScrollView contentContainerStyle={s.content}><View style={s.hero}><Text style={s.heroTitle}>CommunityConnect</Text><Text style={s.heroText}>Legal agreement and usage guidelines</Text></View>{data.map(([title, body]) => <View style={s.card} key={title}><View style={s.head}><View style={s.icon}><Ionicons name="shield-checkmark-outline" size={16} color={colors.lime}/></View><Text style={s.title}>{title}</Text></View><Text style={s.body}>{body}</Text></View>)}<Text style={s.updated}>Last Updated: October 24, 2023</Text><Pressable style={s.accept} onPress={() => navigation.goBack()}><Text style={s.acceptText}>Accept Terms</Text></Pressable><Text style={s.footer}>Questions about our terms? Contact Support</Text></ScrollView></SafeAreaView>; }
;
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, nav: { alignItems: "center", flexDirection: "row", height: 52, paddingHorizontal: 20 }, navTitle: { color: "#079d4c", fontFamily: fonts.bold, fontSize: 14, marginLeft: 16 }, content: { padding: 19, paddingBottom: 38 }, hero: { backgroundColor: "#154531", borderRadius: 24, height: 95, justifyContent: "center", padding: 18 }, heroTitle: { color: colors.white, fontFamily: fonts.extraBold, fontSize: 20 }, heroText: { color: "#d5e5dc", fontFamily: fonts.medium, fontSize: 13 }, card: { backgroundColor: colors.white, borderRadius: 27, elevation: 2, marginTop: 14, padding: 19 }, head: { alignItems: "center", flexDirection: "row", gap: 12 }, icon: { alignItems: "center", backgroundColor: "#eafff0", borderRadius: 15, height: 30, justifyContent: "center", width: 30 }, title: { color: colors.ink, fontFamily: fonts.bold, fontSize: 15 }, body: { color: "#314139", fontFamily: fonts.medium, fontSize: 13, lineHeight: 19, marginTop: 14 }, updated: { color: "#399760", fontFamily: fonts.medium, fontSize: 12, marginTop: 25, textAlign: "center" }, accept: { alignItems: "center", backgroundColor: colors.lime, borderRadius: 24, elevation: 3, height: 49, justifyContent: "center", marginTop: 22 }, acceptText: { color: colors.ink, fontFamily: fonts.bold, fontSize: 14 }, footer: { color: "#6c9b7d", fontFamily: fonts.medium, fontSize: 10, marginTop: 15, textAlign: "center" } });
